### ISSUE TITLE
omicron-us_location-variant-sequence-counts.tsv contains many duplicate rows

### ISSUE THREAD

**Issue by damonbayer** [blab/rt-from-frequency-dynamics#15]
In [omicron-us_location-variant-sequence-counts.tsv](https://github.com/blab/rt-from-frequency-dynamics/blob/e06cca79b64c4e7e8c492cb08797429c1e43328b/data/omicron-us/omicron-us_location-variant-sequence-counts.tsv) from  e06cca7 (committed yesterday), rows 2-50 are identical to rows 51-99. These rows consist of "other" variants from Arizona 2021-10-15 though 2021-12-27. This issue happens again with "other" variants in California from 2021-10-15 to 2021-12-30. Seems to be a different date range for each state, but always with the "other" variant category.

This issue is also present in the previous commit, but I didn't look back further than that.

It's easy enough for me to filter out the duplicates when looking at the data, but I'm not sure if it is indicative of some bigger problem with the data processing.

**Comment by trvrb** [comment]
Thanks for flagging @damonbayer! Commit bdb5aa61393d0faf122467051a81319373719c00 resolves this issue.
